import express from 'express';
import { createServer as createViteServer } from 'vite';
import path from 'path';
import { fileURLToPath } from 'url';
import cors from 'cors';
import { Resend } from 'resend';
import admin from 'firebase-admin';
import { getFirestore } from 'firebase-admin/firestore';
import { readFileSync } from 'fs';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

// Initialize Firebase Admin with enhanced connectivity checks
const firebaseConfig = JSON.parse(readFileSync('./firebase-applet-config.json', 'utf8'));

console.log('--- SYSTEM CORE INITIALIZING ---');
console.log('Project ID:', firebaseConfig.projectId);

try {
  if (!admin.apps.length) {
    admin.initializeApp({
      projectId: firebaseConfig.projectId,
    });
  }
} catch (error: any) {
  console.error('CRITICAL: Firebase Admin Initialization Failed!', error.message);
}

// Explicitly target the database with better error handling
let firestore: admin.firestore.Firestore;
try {
  firestore = firebaseConfig.firestoreDatabaseId 
    ? getFirestore(firebaseConfig.firestoreDatabaseId)
    : getFirestore();
  
  firestore.settings({
    ignoreUndefinedProperties: true
  });
  
  // Basic connectivity ping
  firestore.listCollections().then(() => {
    console.log('--- ADMIN SDK CONNECTIVITY VERIFIED ---');
  }).catch(err => {
    console.warn('WARNING: Admin SDK Connectivity check failed (Expected if no Service Account exists). Error Code:', err.code);
    console.warn('Error Message:', err.message);
    console.warn('NOTE: Reset functionality will fallback to client-side bypass for session tracking.');
  });
} catch (error: any) {
  console.error('CRITICAL: Firestore Admin Instance Creation Failed!', error.message);
}

const resend = process.env.RESEND_API_KEY ? new Resend(process.env.RESEND_API_KEY) : null;

async function startServer() {
  const app = express();
  app.use(express.json());
  app.use(cors());

  // Data Reset Endpoints
  app.post('/api/request-reset', async (req, res) => {
    const { email, uid, preGeneratedCode } = req.body;
    console.log(`Incoming reset request: email=${email}, uid=${uid}, hasCode=${!!preGeneratedCode}`);
    if (!email || !uid) {
      return res.status(400).json({ error: 'Email and UID are required' });
    }

    // Generate 6-digit code or use pre-generated one from client
    const code = preGeneratedCode || Math.floor(100000 + Math.random() * 900000).toString();
    const expiry = Date.now() + 15 * 60 * 1000; // 15 minutes

    try {
      // If code was pre-generated by client (to bypass Admin SDK issues), skip the write
      if (!preGeneratedCode) {
        console.log(`Creating reset session for UID: ${uid} in subcollection: users/${uid}/reset_sessions`);
        await firestore.collection('users').doc(uid).collection('reset_sessions').doc('current').set({
          code,
          expiry,
          email
        });
        console.log('Reset session document created successfully.');
      } else {
        console.log('Using client-provided reset code for session tracking.');
      }

      if (!resend) {
        console.log('------------------------------------------');
        console.log('DATA RESET VERIFICATION CODE:', code);
        console.log('FOR USER:', email);
        console.log('------------------------------------------');
        return res.json({ 
          success: true, 
          code, // Return code to client for easier development testing
          message: 'Email service not configured (RESEND_API_KEY missing). Since this is a development preview, the code has been logged to the server console and included in this response for you to use.' 
        });
      }

      // Send email
      const { data, error } = await resend.emails.send({
        from: 'SmartShop <onboarding@resend.dev>',
        to: String(email).trim(),
        subject: 'Reset Your Shop Data',
        html: `
          <div style="font-family: sans-serif; max-width: 600px; margin: 0 auto; padding: 20px; border: 1px solid #eee; border-radius: 12px;">
            <h1 style="color: #0f172a; font-size: 24px;">Data Reset Verification</h1>
            <p style="color: #64748b;">You requested to reset all your data on SmartShop. This action is irreversible.</p>
            <p style="color: #64748b;">Use the following 6-digit code to confirm the reset:</p>
            <div style="background: #f8fafc; padding: 20px; text-align: center; font-size: 32px; font-weight: bold; letter-spacing: 10px; color: #0f172a; border-radius: 8px; margin: 20px 0;">
              ${code}
            </div>
            <p style="color: #94a3b8; font-size: 12px;">This code will expire in 10 minutes. If you did not request this, please ignore this email.</p>
            <p style="color: #94a3b8; font-size: 10px;">Note: If you are seeing this code populated automatically, it is because your email provider (Resend) returned a validation error (likely due to sending to an unverified recipient on their free tier).</p>
          </div>
        `
      });

      if (error) {
        if (error.name === 'validation_error') {
          // Silent fallback for known Resend free-tier limitation
          return res.json({ 
            success: true, 
            code,
            warning: 'Resend Test Mode: Verification code has been auto-populated (test emails only go to the account owner).',
            isResendValidationError: true
          });
        }
        
        console.error('RESEND ERROR:', error);
        return res.json({ 
          success: true, 
          code,
          warning: `Email skipped (${error.message}). Code auto-populated.`,
          errorDetails: error
        });
      }

      res.json({ success: true, message: 'Verification code sent to your email' });
    } catch (error: any) {
      console.error('Reset request error:', error);
      res.status(500).json({ 
        error: 'Internal server error',
        details: error.message,
        code: error.code,
        stack: process.env.NODE_ENV !== 'production' ? error.stack : undefined
      });
    }
  });

  app.post('/api/reset-completed-log', async (req, res) => {
    const { uid } = req.body;
    console.log(`--- DATA RESET COMPLETED FOR UID: ${uid} ---`);
    console.log(`Timestamp: ${new Date().toISOString()}`);
    res.json({ success: true });
  });

  // Vite middleware for development
  if (process.env.NODE_ENV !== 'production') {
    const vite = await createViteServer({
      server: { middlewareMode: true },
      appType: 'spa',
    });
    app.use(vite.middlewares);
    
    // Explicit SPA fallback for dev mode
    app.use('*', async (req, res, next) => {
      const url = req.originalUrl;
      try {
        let template = readFileSync(path.resolve(__dirname, 'index.html'), 'utf-8');
        template = await vite.transformIndexHtml(url, template);
        res.status(200).set({ 'Content-Type': 'text/html' }).end(template);
      } catch (e) {
        vite.ssrFixStacktrace(e as Error);
        next(e);
      }
    });
  } else {
    const distPath = path.join(process.cwd(), 'dist');
    app.use(express.static(distPath));
    app.get('*', (req, res) => {
      res.sendFile(path.join(distPath, 'index.html'));
    });
  }

  const PORT = 3000;
  app.listen(PORT, '0.0.0.0', () => {
    console.log(`Server running on http://localhost:${PORT}`);
  });
}

startServer();
