import express from 'express';
import { createServer as createViteServer } from 'vite';
import path from 'path';
import { fileURLToPath } from 'url';
import cors from 'cors';
import { Resend } from 'resend';
import admin from 'firebase-admin';
import { getFirestore } from 'firebase-admin/firestore';
import { readFileSync } from 'fs';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

// Initialize Firebase Admin
const firebaseConfig = JSON.parse(readFileSync('./firebase-applet-config.json', 'utf8'));

// FORCE the environment to match the config before ANY SDK calls
if (firebaseConfig.projectId) {
  process.env.GOOGLE_CLOUD_PROJECT = firebaseConfig.projectId;
  process.env.GCP_PROJECT = firebaseConfig.projectId;
}

// Reset any existing apps to start fresh
if (admin.apps.length) {
  await Promise.all(admin.apps.map(app => app?.delete().catch(() => {})));
}

// Initialize the default app
admin.initializeApp({
  projectId: firebaseConfig.projectId,
});

// Explicitly target the database
const firestore = firebaseConfig.firestoreDatabaseId 
  ? getFirestore(firebaseConfig.firestoreDatabaseId)
  : getFirestore();

firestore.settings({
  ignoreUndefinedProperties: true
});

console.log('--- SYSTEM CORE INITIALIZED ---');
console.log('Project Scoping:', firebaseConfig.projectId);
console.log('Database Targeting:', firebaseConfig.firestoreDatabaseId || '(default)');

// Startup Sanity Check
(async () => {
  try {
    console.log('Verifying Admin SDK database connectivity...');
    // Try to list a single doc from any collection to verify permissions
    await firestore.collection('shop_reset_sessions').limit(1).get();
    console.log('Admin SDK connectivity: VERIFIED (OK)');
  } catch (err: any) {
    console.error('CRITICAL: Admin SDK Connectivity check failed!');
    console.error('Error Code:', err.code);
    console.error('Error Message:', err.message);
  }
})();

const resend = process.env.RESEND_API_KEY ? new Resend(process.env.RESEND_API_KEY) : null;

async function startServer() {
  const app = express();
  app.use(express.json());
  app.use(cors());

  // Data Reset Endpoints
  app.post('/api/request-reset', async (req, res) => {
    const { email, uid, preGeneratedCode } = req.body;
    if (!email || !uid) {
      return res.status(400).json({ error: 'Email and UID are required' });
    }

    // Generate 6-digit code or use pre-generated one from client
    const code = preGeneratedCode || Math.floor(100000 + Math.random() * 900000).toString();
    const expiry = Date.now() + 15 * 60 * 1000; // 15 minutes

    try {
      // If code was pre-generated by client (to bypass Admin SDK issues), skip the write
      if (!preGeneratedCode) {
        console.log(`Creating reset session for UID: ${uid} in collection: shop_reset_sessions`);
        await firestore.collection('shop_reset_sessions').doc(uid).set({
          code,
          expiry,
          email
        });
        console.log('Reset session document created successfully.');
      } else {
        console.log('Using client-provided reset code for session tracking.');
      }

      if (!resend) {
        console.log('------------------------------------------');
        console.log('DATA RESET VERIFICATION CODE:', code);
        console.log('FOR USER:', email);
        console.log('------------------------------------------');
        return res.json({ 
          success: true, 
          code, // Return code to client for easier development testing
          message: 'Email service not configured (RESEND_API_KEY missing). Since this is a development preview, the code has been logged to the server console and included in this response for you to use.' 
        });
      }

      // Send email
      const { data, error } = await resend.emails.send({
        from: 'SmartShop <onboarding@resend.dev>',
        to: [email],
        subject: 'Reset Your Shop Data',
        html: `
          <div style="font-family: sans-serif; max-width: 600px; margin: 0 auto; padding: 20px; border: 1px solid #eee; rounded: 12px;">
            <h1 style="color: #0f172a; font-size: 24px;">Data Reset Verification</h1>
            <p style="color: #64748b;">You requested to reset all your data on SmartShop. This action is irreversible.</p>
            <p style="color: #64748b;">Use the following 6-digit code to confirm the reset:</p>
            <div style="background: #f8fafc; padding: 20px; text-align: center; font-size: 32px; font-weight: bold; letter-spacing: 10px; color: #0f172a; border-radius: 8px; margin: 20px 0;">
              ${code}
            </div>
            <p style="color: #94a3b8; font-size: 12px;">This code will expire in 10 minutes. If you did not request this, please ignore this email.</p>
          </div>
        `
      });

      if (error) {
        console.error('Email error:', error);
        return res.status(500).json({ error: 'Failed to send verification email' });
      }

      res.json({ success: true, message: 'Verification code sent to your email' });
    } catch (error: any) {
      console.error('Reset request error:', error);
      res.status(500).json({ 
        error: 'Internal server error',
        details: error.message,
        code: error.code,
        stack: process.env.NODE_ENV !== 'production' ? error.stack : undefined
      });
    }
  });

  app.post('/api/reset-completed-log', async (req, res) => {
    const { uid } = req.body;
    console.log(`--- DATA RESET COMPLETED FOR UID: ${uid} ---`);
    console.log(`Timestamp: ${new Date().toISOString()}`);
    res.json({ success: true });
  });

  // Vite middleware for development
  if (process.env.NODE_ENV !== 'production') {
    const vite = await createViteServer({
      server: { middlewareMode: true },
      appType: 'spa',
    });
    app.use(vite.middlewares);
    
    // Explicit SPA fallback for dev mode
    app.use('*', async (req, res, next) => {
      const url = req.originalUrl;
      try {
        let template = readFileSync(path.resolve(__dirname, 'index.html'), 'utf-8');
        template = await vite.transformIndexHtml(url, template);
        res.status(200).set({ 'Content-Type': 'text/html' }).end(template);
      } catch (e) {
        vite.ssrFixStacktrace(e as Error);
        next(e);
      }
    });
  } else {
    const distPath = path.join(process.cwd(), 'dist');
    app.use(express.static(distPath));
    app.get('*', (req, res) => {
      res.sendFile(path.join(distPath, 'index.html'));
    });
  }

  const PORT = 3000;
  app.listen(PORT, '0.0.0.0', () => {
    console.log(`Server running on http://localhost:${PORT}`);
  });
}

startServer();
